spring:
  application:
    name: account
  datasource:
    url: jdbc:mysql://192.168.0.162/im?serverTimezone=GMT
    username: root
    password: 123456
  redis:
    host: 192.168.2.221
    port: 6379
    timeout: 3000
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.15.43:8848
      config:
        server-addr: 192.168.15.43:8848
        file-extension: yaml
server:
  port: 8001

management:
  endpoints:
    web:
      exposure:
        include: "*"

sa-token:
  is-concurrent: false

mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
