spring:
  application:
    name: account
  profiles:
    active: ${profiles.active:prod}

server:
  port: ${SERVER_PORT}

sa-token:
  token-name: token
  is-concurrent: false
  is-log: true

mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl