spring:
  application:
    name: chat
  profiles:
    active: ${profiles.active:prod}

server:
  port: ${SERVER_PORT}

chat-address: ${CHAT_ADDRESS}

mybatis:
  mapper-locations: classpath:mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
