spring:
  application:
    name: file
  profiles:
    active: ${profiles.active:prod}
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.entity

server:
  port: ${SERVER_PORT}

