spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.162:3306/im?serverTimezone=GMT
    username: root
    password: 123456
  #    url: jdbc:mysql://82.156.59.244:3306/mytest?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
  #    username: mytest
  #    password: S6zs7KzMCJjsR6ys
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.15.43:8848
      config:
        server-addr: 192.168.15.43:8848
        file-extension: yaml