#多个环境的共同配置
spring:
  application:
    name: gateway
  profiles:
    active: "@profiles.active@"
  cloud:
    gateway:
      routes:
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods: '*'

sa-token:
  token-name: token
  is-concurrent: false
  is-log: true

server:
  port: 4396