#多个环境的共同配置
spring:
  application:
    name: gateway
  profiles:
    active: ${profiles.active:prod}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST
      routes:
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
        - id: ws
          uri: lb://connection
          predicates:
            - Path=/ws/**
          filters:
            - RemoveRequestHeader=Sec-WebSocket-Protocol

sa-token:
  token-name: token
  is-concurrent: false
  is-log: true

server:
  port: ${SERVER_PORT}