spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account
          uri: lb://account
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders: '*'
            allowedMethods: '*'
    nacos:
      discovery:
        server-addr: 192.168.15.43:8848
      config:
        server-addr: 192.168.15.43:8848
        file-extension: yaml
server:
  port: 4396